### ISSUE TITLE
does it still work?

### ISSUE THREAD

**Issue by StahlhelmTV** [CedArctic/Chimera#20]
i mae everything and when i try to run chimera.py in powershell nothing happens
![Unbenannt](https://user-images.githubusercontent.com/47715580/57975930-ebf15480-79d4-11e9-9df3-a131f6f4a51a.PNG)
[2019-05-19.txt](https://github.com/CedArctic/Chimera/files/3194599/2019-05-19.txt)

**Comment by StahlhelmTV** [comment]
fixed the token problem but now i get this one: 
--------
Chimera Remote Administration Bot by CedArctic
--------
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\james\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 251, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\james\Downloads\Chimera-master\Chimera-master\chimera.py", line 52, in on_ready
    str(len(client.servers))+' servers | Connected to '+str(len(set(client.get_all_members())))+' users')
TypeError: must be str, not int

**Comment by CedArctic** [comment]
Apologies for the late reply. Just released an update for the project. Everything should be working now. Let me know if you still have any issues.
