### ISSUE TITLE
Chimera won't open.

### ISSUE THREAD

**Issue by vlad4him** [CedArctic/Chimera#3]
Hi there can anyone help me figure out why chimera won't open.This is what it shows me after i run python chimera_Windows.py
                              ^
SyntaxError: invalid syntax
PS C:\Users\V\Desktop> python chimera_Windows.py
Traceback (most recent call last):
  File "chimera_Windows.py", line 2, in <module>
    import discord
  File "C:\Users\V\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\V\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\V\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\V\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

**Comment by vlad4him** [comment]
> 
> 
> Have you used pip to install mss and discord.py? Also did you copy and paste the script in notepad or did you download it directly from Github?

I installed discord.py and i downloaded the repository from git and created a copy of the script file on my desktop.

**Comment by vlad4him** [comment]
I forked the github  then cloned the repository . I used pip install
discord.py mss and it worked.

**Comment by vlad4him** [comment]
I figured it out.Chimera only works with python 3.6.5.
